[package]
name = "rust_lib_photos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
image = "0.25.4"
resize = "0.8.7"
rgb = "0.8.50"
bytemuck = "1.16.0"
